export const PLAYER_PLAY = 'PLAYER_PLAY'
export const PLAYER_PAUSE = 'PLAYER_PAUSE'
export const SET_TRACK = 'SET_TRACK'

export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST'
export const PLAYER_NEXT = 'PLAYER_NEXT'
export const PLAYER_PREV = 'PLAYER_PREV'
export const TRACK_ENDS = 'TRACK_ENDS'

export const SET_VOLUME = 'SET_VOLUME'
export const TOGGLE_MUTE = 'TOGGLE_MUTE'
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT'

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
export const RENAME_PLAYLIST = 'RENAME_PLAYLIST'
export const CLOSE_OPEN_PLAYLIST = 'CLOSE_OPEN_PLAYLIST'
export const CLOSE_OTHER_PLAYLISTS = 'CLOSE_OTHER_PLAYLISTS'

export const DEFAULT_PL = 'Default'
export const ARTIST_PL = '__Artist__'
export const SEARCH_PL = '__Search__'

export const MOVE_TRACK = 'MOVE_TRACK'
export const REMOVE_TRACK = 'REMOVE_TRACK'
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST'

export const SORT_PLAYLIST = 'SORT_PLAYLIST'
export const BY_TITLE = 'BY_TITLE'
export const BY_ARTIST = 'BY_ARTIST'
export const BY_DURATION = 'BY_DURATION'
export const BY_PATH = 'BY_PATH'
export const SHUFFLE = 'SHUFFLE'
export const REVERSE = 'REVERSE'

export const SELECT_TAB = 'SELECT_TAB'
export const SCROLL_LEFT = 'SCROLL_LEFT'
export const SCROLL_RIGHT = 'SCROLL_RIGHT'

export const TRACK_DRAG_START = 'TRACK_DRAG_START'
export const TRACK_DRAG_END = 'TRACK_DRAG_END'
export const TRACK_DRAG_DROP = 'TRACK_DRAG_DROP'
export const TRACK_DRAG_DROP_DELETE = 'TRACK_DRAG_DROP_DELETE'

export const GET_RANDOM_TRACKS_REQUEST = 'GET_RANDOM_TRACKS_REQUEST'
export const GET_RANDOM_TRACKS_SUCCESS = 'GET_RANDOM_TRACKS_SUCCESS'
export const GET_RANDOM_TRACKS_FAILED = 'GET_RANDOM_TRACKS_FAILED'

export const CUT_OBSOLETE_RANDOM_TRACKS = 'CUT_OBSOLETE_RANDOM_TRACKS'
export const CHANGE_RANDOM_FILTER = 'CHANGE_RANDOM_FILTER'
