export const OPEN_PLAYLIST_DIALOG_SELECT_LOCAL_TAB = 'OPEN_PLAYLIST_DIALOG_SELECT_LOCAL_TAB'

export const STORAGE_LOAD_PLAYLISTS_SUCCESS = 'STORAGE_LOAD_PLAYLISTS_SUCCESS'
export const STORAGE_SAVE_PLAYLIST_SUCCESS = 'STORAGE_SAVE_PLAYLIST_SUCCESS'
export const STORAGE_OPEN_PLAYLIST_SUCCESS = 'STORAGE_OPEN_PLAYLIST_SUCCESS'
export const STORAGE_DELETE_PLAYLIST_SUCCESS = 'STORAGE_DELETE_PLAYLIST_SUCCESS'

export const GET_SERVER_PLAYLISTS_REQUEST = 'GET_SERVER_PLAYLISTS_REQUEST'
export const GET_SERVER_PLAYLISTS_SUCCESS = 'GET_SERVER_PLAYLISTS_SUCCESS'
export const GET_SERVER_PLAYLISTS_FAILED = 'GET_SERVER_PLAYLISTS_FAILED'

export const PUT_SERVER_PLAYLIST_REQUEST = 'PUT_SERVER_PLAYLIST_REQUEST'
export const PUT_SERVER_PLAYLIST_SUCCESS = 'PUT_SERVER_PLAYLIST_SUCCESS'
export const PUT_SERVER_PLAYLIST_FAILED = 'PUT_SERVER_PLAYLIST_FAILED'

export const DELETE_SERVER_PLAYLIST_REQUEST = 'DELETE_SERVER_PLAYLIST_REQUEST'
export const DELETE_SERVER_PLAYLIST_SUCCESS = 'DELETE_SERVER_PLAYLIST_SUCCESS'
export const DELETE_SERVER_PLAYLIST_FAILED = 'DELETE_SERVER_PLAYLIST_FAILED'

export const STORAGE_SERVER_OPEN_PLAYLIST = 'STORAGE_OPEN_SERVER_PLAYLIST'
